---
version: "2.1"
services:
  db:
    image: postgres:10.6
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 1s
      retries: 60
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy